controllers/AdminController.php
<?php 
	namespace app\controllers;
	use Yii;
	use yii\helpers\Url;
	use yii\web\Controller;
	use app\models\Member;
	use app\helpers\MyHelper;
	class AdminController extends Controller{
		public $layout = 'admin';

		public function beforeAction($action) {
	        if ($action->id != 'login'
				&& $action->id != 'auth'
				&&(Yii::$app->user->getIsGuest() || MyHelper::isAdmin() == false)) {
	            $this->redirect(Url::to(['admin/login']));
	        } else
	        return parent::beforeAction($action);
	    }

	    public function actions()
	    {
	        return [
	            'error' => [
	                'class' => 'yii\web\ErrorAction',
	            ],
	            'captcha' => [
	                'class' => 'yii\captcha\CaptchaAction',
	                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
	            ],
	            'auth' => [
	                'class' => 'yii\authclient\AuthAction',
	                'successCallback' => [$this, 'successCallback'],
	            ],
	        ];
	    }

	    public function successCallback($client)
	    {
	    	$attributes = $client->getUserAttributes();
		    $email = $attributes['emails'][0]['value'];
		    $name = isset($attributes['displayName'])? $attributes['displayName']:""; 
		    $member = Member::checkMember($email, $name);
	    	$member->login(0);   
		    Yii::$app->session['email'] = $email;
		    Yii::$app->session['name'] = $name;
		    $member = Member::findByEmail($email);
		    Yii::$app->session['id'] = $member->id; 
		    Yii::$app->session['role_id'] = $member->role_id;
		    $this->redirect(Url::to(['admin/index']));
	    }
		
		public function actionLogin(){
			$model = new Member();
			return $this->render('login', ['model' => $model]);
		}

		public function actionLogout(){
			Yii::$app->user->logout();
			$this->redirect(Url::to(['admin/login']));
		}

		public function actionIndex(){
			$this->layout = 'sbadmin/index';
			return $this->render('index');
		}
	}
 ?>

controllers/AdminNotificationController.php
<?php
    namespace app\controllers;

    use yii\web\Controller;
    use app\models\JoinTeam;
    use yii\helpers\Url;
    use app\helpers\MyHelper;
    use Yii;

    class AdminNotificationController extends Controller{
        public $layout = 'sbadmin/index';

        public function beforeAction($action) {
            if ($action->id != 'login'
                && $action->id != 'auth'
                &&(Yii::$app->user->getIsGuest() || MyHelper::isAdmin() == false)) {
                $this->redirect(Url::to(['admin/login']));
            } else
                return parent::beforeAction($action);
        }
        public function actionIndex(){
            $join_teams = JoinTeam::find()
                ->where(['active' => 0])
                ->orderBy('team_id')
                ->all();
            $out_teams = JoinTeam::find()
                ->where(['active' => -1])
                ->orderBy('team_id')
                ->all();
            return $this->render('index', ['join_teams' => $join_teams, 'out_teams' => $out_teams]);
        }
    }
?>

views/layouts/sbadmin/index.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Url;
use app\helpers\MyUrl;
use app\models\JoinTeam;
use app\assets\AdminAsset;
?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Kaopiz's Profile Admin</title>
    <!-- CSS My Admin -->
    <link href="/kaopiz_profile_new/web/css/admin.css" rel="stylesheet">

    <!-- Bootstrap Core CSS -->
    <link href="/kaopiz_profile_new/views/layouts/sbadmin/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/kaopiz_profile_new/views/layouts/sbadmin/css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/kaopiz_profile_new/views/layouts/sbadmin/css/plugins/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/kaopiz_profile_new/views/layouts/sbadmin/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= Url::to(["admin/index"]);?>">Kaopiz's Profile Admin</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php echo !empty(Yii::$app->session['name'])? Yii::$app->session['name']:  'Admin'?><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?= Url::to(["admin-member/view?id=".Yii::$app->user->id]);?>"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?= Url::to(["admin/logout"]);?>"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="<?= Url::to(["admin/index"]);?>"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="<?= Url::to(["admin-member/index"]);?>"><i class="fa fa-users"></i> Member</a>
                    </li>
                    <li>
                        <a href="<?= Url::to(["admin-team/index"]);?>"><i class="fa fa-fw fa-table"></i> Team</a>
                    </li>
                    <li>
                        <a href="<?= Url::to(["admin-role/index"]);?>"><i class="fa fa-fw fa-edit"></i> Role</a>
                    </li>
                    <li>
                        <a href="<?= Url::to(["admin-image/index"]);?>"><i class="fa fa-fw fa-image"></i> Images</a>
                    </li>
                    <li>
                        <a href="<?= Url::to(["admin-notification/index"]);?>"><i class="fa fa-bell"></i><?php echo JoinTeam::getNumberNofi()!=0? ' Notification('.JoinTeam::getNumberNofi().')':' Notification'?></a>
                    </li>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                
                <div id="my-admin-content">
                    <?= $content?>
                </div>


            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <script src="/kaopiz_profile_new/web/js/admin.js"></script>
    <!-- jQuery -->
    <script src="/kaopiz_profile_new/views/layouts/sbadmin/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/kaopiz_profile_new/views/layouts/sbadmin/js/bootstrap.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="/kaopiz_profile_new/views/layouts/sbadmin/js/plugins/morris/raphael.min.js"></script>
    <script src="/kaopiz_profile_new/views/layouts/sbadmin/js/plugins/morris/morris.min.js"></script>
    <script src="/kaopiz_profile_new/views/layouts/sbadmin/js/plugins/morris/morris-data.js"></script>

</body>

</html>

views/layouts/sbadmin/login.php
<!DOCTYPE html>
<html lang="en">
<head>
	
	<!-- start: Meta -->
	<meta charset="utf-8">
	<title>Bootstrap Metro Dashboard by Dennis Ji for ARM demo</title>
	<meta name="description" content="Bootstrap Metro Dashboard">
	<meta name="author" content="Dennis Ji">
	<meta name="keyword" content="Metro, Metro UI, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: CSS -->
	<link id="bootstrap-style" href="/profile1/views/layouts/sbadmin/metro/css/bootstrap.min.css" rel="stylesheet">
	<link href="/profile1/views/layouts/sbadmin/metro/css/bootstrap-responsive.min.css" rel="stylesheet">
	<link id="base-style" href="/profile1/views/layouts/sbadmin/metro/css/style.css" rel="stylesheet">
	<link id="base-style-responsive" href="/profile1/views/layouts/sbadmin/metro/css/style-responsive.css" rel="stylesheet">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>
	<!-- end: CSS -->
	

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<link id="ie-style" href="/profile1/views/layouts/sbadmin/metro/css/ie.css" rel="stylesheet">
	<![endif]-->
	
	<!--[if IE 9]>
		<link id="ie9style" href="/profile1/views/layouts/sbadmin/metro/css/ie9.css" rel="stylesheet">
	<![endif]-->
		
	<!-- start: Favicon -->
	<link rel="shortcut icon" href="/profile1/views/layouts/sbadmin/metro/img/favicon.ico">
	<!-- end: Favicon -->
	
		<style type="text/css">
			body { background: url(/profile1/views/layouts/sbadmin/metro/img/bg-login.jpg) !important; }
		</style>
		
		
		
</head>

<body>
		<div class="container-fluid-full">
		<div class="row-fluid">
					
			<div class="row-fluid">
				<div class="login-box">

					<h2>Login to your account</h2>
					<form class="form-horizontal" action="index.html" method="post">
						<fieldset>
							
							<div class="input-prepend" title="Username">
								<span class="add-on"><i class="halflings-icon user"></i></span>
								<input class="input-large span10" name="username" id="username" type="text" placeholder="type username"/>
							</div>
							<div class="clearfix"></div>

							<div class="input-prepend" title="Password">
								<span class="add-on"><i class="halflings-icon lock"></i></span>
								<input class="input-large span10" name="password" id="password" type="password" placeholder="type password"/>
							</div>
							<div class="clearfix"></div>
							
							<label class="remember" for="remember"><input type="checkbox" id="remember" />Remember me</label>

							<div class="button-login">	
								<button type="submit" class="btn btn-primary">Login</button>
							</div>
							<?= yii\authclient\widgets\AuthChoice::widget([
									'baseAuthUrl' => ['admin/auth'],
									'popupMode' => false,
								]);
							?>
							<div class="clearfix"></div>
					</form>
					<hr>
					<h3>Forgot Password?</h3>
					<p>
						No problem, <a href="#">click here</a> to get a new password.
					</p>	
				</div><!--/span-->
			</div><!--/row-->
			

	</div><!--/.fluid-container-->
	
		</div><!--/fluid-row-->
	
	<!-- start: JavaScript-->


</body>
</html>